version: "3.8"

services:
  maruko-project:
    image: arifhdyt72/maruko-project:latest
    ports:
      - "5544:5544"
    deploy:
      mode: replicated
      replicas: 4
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 5
        window: 30s
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5544/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
